# Manipulação de arrays Numpy

### Importando o NumPy

In [1]:
# Importando o NumPy
import numpy as np

### Alterando, adicionando e removendo elementos

In [2]:
# Criando um array de 1 dimensão
a1D = np.random.randint(1,200, 12)
a1D

array([ 66, 124,  64, 157, 146, 183,  70,   7,  46, 106,  32, 187])

In [3]:
# Criando um array de 2 dimensões
a2D = np.random.randint(1,200, (3,4))
a2D

array([[128,  96,  56, 141],
       [ 72,  36,  53,   6],
       [149,  94, 119, 194]])

In [4]:
# Criando um array de 3 dimensões
a3D = np.random.randint(1,200, (2,3,6)) # 2 páginas/faces, 3 linhas, 6 colunas
a3D

array([[[ 40, 122,  70, 102, 152,  36],
        [102, 156,  95, 168, 165, 111],
        [ 57,  89, 133,  48,  27, 106]],

       [[ 98,  75, 124, 166,  62,  94],
        [174, 141,  89,  90, 116,  35],
        [109, 153,  75, 162,  62,  53]]])

In [5]:
# Alterando o elemento do índice 0
a1D[0] = -1
a1D

array([ -1, 124,  64, 157, 146, 183,  70,   7,  46, 106,  32, 187])

In [6]:
# Alterando o elemento da linha 1, coluna 2
a2D[1][2] = -1
a2D

array([[128,  96,  56, 141],
       [ 72,  36,  -1,   6],
       [149,  94, 119, 194]])

In [7]:
# Alterando o elemento da face 1, linha 2, coluna 4
a3D[1][2][4] = -1
a3D

array([[[ 40, 122,  70, 102, 152,  36],
        [102, 156,  95, 168, 165, 111],
        [ 57,  89, 133,  48,  27, 106]],

       [[ 98,  75, 124, 166,  62,  94],
        [174, 141,  89,  90, 116,  35],
        [109, 153,  75, 162,  -1,  53]]])

In [8]:
# Retorna array com elementos adicionados no final
a1D_modificado = np.append(a1D, [100, 130])
a1D_modificado

array([ -1, 124,  64, 157, 146, 183,  70,   7,  46, 106,  32, 187, 100,
       130])

In [9]:
a1D # a1D não foi modificado

array([ -1, 124,  64, 157, 146, 183,  70,   7,  46, 106,  32, 187])

In [10]:
a2D_modificado = np.append(a2D, [100, 130]) # Lineariza a2D e insere os elementos no final
a2D_modificado

array([128,  96,  56, 141,  72,  36,  -1,   6, 149,  94, 119, 194, 100,
       130])

In [11]:
a2D # a2D não foi modificado

array([[128,  96,  56, 141],
       [ 72,  36,  -1,   6],
       [149,  94, 119, 194]])

In [12]:
a3D_modificado = np.append(a3D, [100, 130]) # Lineariza a3D e insere os elementos no final
a3D_modificado

array([ 40, 122,  70, 102, 152,  36, 102, 156,  95, 168, 165, 111,  57,
        89, 133,  48,  27, 106,  98,  75, 124, 166,  62,  94, 174, 141,
        89,  90, 116,  35, 109, 153,  75, 162,  -1,  53, 100, 130])

In [13]:
a3D # a3D não foi modificado

array([[[ 40, 122,  70, 102, 152,  36],
        [102, 156,  95, 168, 165, 111],
        [ 57,  89, 133,  48,  27, 106]],

       [[ 98,  75, 124, 166,  62,  94],
        [174, 141,  89,  90, 116,  35],
        [109, 153,  75, 162,  -1,  53]]])

In [14]:
a1D_modificado2 = np.delete(a1D_modificado, [0, 1, 3])
print(a1D_modificado)
print(a1D_modificado2)

[ -1 124  64 157 146 183  70   7  46 106  32 187 100 130]
[ 64 146 183  70   7  46 106  32 187 100 130]


### Comparação entre arrays

In [15]:
a1D = np.array([1, 2, 3, 4, 5])
b1D = np.array([3, 2, 1, 4, 5])
a1D == b1D # Comparação elemento a elemento

array([False,  True, False,  True,  True])

In [16]:
c1D = np.random.randint(1,10,20)
c1D

array([7, 1, 3, 7, 5, 7, 7, 6, 7, 9, 2, 4, 9, 2, 7, 6, 5, 7, 2, 9])

In [17]:
c1D == 5

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False])

In [18]:
c1D[c1D == 5]

array([5, 5])

### Operações entre arrays e escalares

In [19]:
a1D = np.arange(1,11)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
b1D = np.arange(1,20,2)
b1D

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
c1D = 2 * a1D # Cada elemento de a1D será multiplicado por 2
c1D

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
d1D = b1D + 5 # Soma 5 para cada elemento de b1D
d1D

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [23]:
e1D = b1D - 3
e1D

array([-2,  0,  2,  4,  6,  8, 10, 12, 14, 16])

In [24]:
f1D = a1D / 5
f1D

array([0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [25]:
celsius = np.arange(-20, 36) # Cria um array com o valores de -20 a 35, representando a temperatura em graus Celsius
fahrenheit = celsius * (9/5) + 32 # Cria um array convertendo cada valor em Celsius para fahrenheit

fahrenheit

array([-4. , -2.2, -0.4,  1.4,  3.2,  5. ,  6.8,  8.6, 10.4, 12.2, 14. ,
       15.8, 17.6, 19.4, 21.2, 23. , 24.8, 26.6, 28.4, 30.2, 32. , 33.8,
       35.6, 37.4, 39.2, 41. , 42.8, 44.6, 46.4, 48.2, 50. , 51.8, 53.6,
       55.4, 57.2, 59. , 60.8, 62.6, 64.4, 66.2, 68. , 69.8, 71.6, 73.4,
       75.2, 77. , 78.8, 80.6, 82.4, 84.2, 86. , 87.8, 89.6, 91.4, 93.2,
       95. ])

In [26]:
# Somando cada elemento de a1D a b1D
g1D = a1D + b1D
print(a1D)
print(b1D)
print("-"*31)
print(g1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [27]:
# Outra forma de somar cada elemento de a1D a b1D
h1D = np.add(a1D, b1D)
print(a1D)
print(b1D)
print("-"*31)
print(h1D)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19]
-------------------------------
[ 2  5  8 11 14 17 20 23 26 29]


In [28]:
i1D = h1D - g1D
print(h1D)
print(g1D)
print("-"*31)
print(i1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [29]:
# Outra forma de somar cada elemento de a1D a b1D
j1D = np.subtract(h1D, g1D)
print(h1D)
print(g1D)
print("-"*31)
print(j1D)

[ 2  5  8 11 14 17 20 23 26 29]
[ 2  5  8 11 14 17 20 23 26 29]
-------------------------------
[0 0 0 0 0 0 0 0 0 0]


In [30]:
a1D = np.arange(1, 6)
a1D

array([1, 2, 3, 4, 5])

In [31]:
b1D = np.arange(6,11)
b1D

array([ 6,  7,  8,  9, 10])

In [32]:
c1D = a1D * b1D
c1D

array([ 6, 14, 24, 36, 50])

In [33]:
d1D = np.multiply(a1D, b1D)
d1D

array([ 6, 14, 24, 36, 50])

In [34]:
e1D = c1D / a1D
e1D

array([ 6.,  7.,  8.,  9., 10.])

In [35]:
f1D = np.divide(c1D, a1D)
f1D

array([ 6.,  7.,  8.,  9., 10.])

In [36]:
g1D = np.arange(1,10)
g1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
raiz1D = np.sqrt(g1D)
raiz1D

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

### Algumas funções

In [38]:
d2D = np.random.randint(1, 101, (5,10)) # Array de 5 linhas x 10 colunas preenchidos com valores aleatórios entre 1 e 100
d2D

array([[ 39,  55,  72,  84,  62,  81,  77,  92,  93,  12],
       [ 42,   1,  53,  22,  32,  13,  71,  94,  21,  29],
       [100,  29,  24,  88,  13,  52,  25,  13,  94, 100],
       [ 35,  43,  20,  19,  53,  27,  14,   3,  78,  28],
       [ 88,  81,  92,  94,  23,  24,  61,  57,  30,  54]])

#### Obs: como os valores valores são gerados aleatoriamente, sua matriz provavelmente será diferente da gerada acima

In [39]:
# Soma de todos os elementos
d2D.sum()

2507

In [40]:
# Soma de todos os elementos de cada coluna (eixo 0)
d2D.sum(axis = 0)

array([304, 209, 261, 307, 183, 197, 248, 259, 316, 223])

In [41]:
# Soma de todos os elementos de cada linha (eixo 1)
d2D.sum(axis = 1)

array([667, 378, 538, 320, 604])

In [42]:
somacol = sum(d2D) # A função sum() do Python retornará a soma de todas as colunas
somacol

array([304, 209, 261, 307, 183, 197, 248, 259, 316, 223])

In [43]:
# Retorna o menor valor geral
d2D.min()

1

In [44]:
# Retorna o menor valor de cada coluna (eixo 0)
d2D.min(axis=0)

array([35,  1, 20, 19, 13, 13, 14,  3, 21, 12])

In [45]:
# Retorna o menor valor de cada linha (eixo 1)
d2D.min(axis=1)

array([12,  1, 13,  3, 23])

In [46]:
# Retorna o maior valor geral
d2D.max()

100

In [47]:
# Retorna o maior valor de cada coluna (eixo 0)
d2D.max(axis=0)

array([100,  81,  92,  94,  62,  81,  77,  94,  94, 100])

In [48]:
# Retorna o maior valor de cada linha (eixo 1)
d2D.max(axis=1)

array([ 93,  94, 100,  78,  94])

In [49]:
# Retorna a soma cumulativa
d2D.cumsum()

array([  39,   94,  166,  250,  312,  393,  470,  562,  655,  667,  709,
        710,  763,  785,  817,  830,  901,  995, 1016, 1045, 1145, 1174,
       1198, 1286, 1299, 1351, 1376, 1389, 1483, 1583, 1618, 1661, 1681,
       1700, 1753, 1780, 1794, 1797, 1875, 1903, 1991, 2072, 2164, 2258,
       2281, 2305, 2366, 2423, 2453, 2507], dtype=int32)

In [50]:
# Retorna a soma cumulativa para cada coluna (eixo = 0)
d2D.cumsum(axis = 0)

array([[ 39,  55,  72,  84,  62,  81,  77,  92,  93,  12],
       [ 81,  56, 125, 106,  94,  94, 148, 186, 114,  41],
       [181,  85, 149, 194, 107, 146, 173, 199, 208, 141],
       [216, 128, 169, 213, 160, 173, 187, 202, 286, 169],
       [304, 209, 261, 307, 183, 197, 248, 259, 316, 223]], dtype=int32)

In [51]:
d2D

array([[ 39,  55,  72,  84,  62,  81,  77,  92,  93,  12],
       [ 42,   1,  53,  22,  32,  13,  71,  94,  21,  29],
       [100,  29,  24,  88,  13,  52,  25,  13,  94, 100],
       [ 35,  43,  20,  19,  53,  27,  14,   3,  78,  28],
       [ 88,  81,  92,  94,  23,  24,  61,  57,  30,  54]])

In [52]:
# Retorna a soma cumulativa para cada linha (eixo = 1)
x = d2D.cumsum(axis = 1)
x

array([[ 39,  94, 166, 250, 312, 393, 470, 562, 655, 667],
       [ 42,  43,  96, 118, 150, 163, 234, 328, 349, 378],
       [100, 129, 153, 241, 254, 306, 331, 344, 438, 538],
       [ 35,  78,  98, 117, 170, 197, 211, 214, 292, 320],
       [ 88, 169, 261, 355, 378, 402, 463, 520, 550, 604]], dtype=int32)

In [53]:
# Retorna a média aritmética
d2D.mean()

50.14

In [54]:
# Retorna a média aritmética para cada coluna (eixo = 0)
d2D.mean(axis = 0)

array([60.8, 41.8, 52.2, 61.4, 36.6, 39.4, 49.6, 51.8, 63.2, 44.6])

In [55]:
# Retorna a média aritmética para cada linha (eixo = 1)
d2D.mean(axis = 1)

array([66.7, 37.8, 53.8, 32. , 60.4])

In [56]:
# Retorna o desvio padrão
d2D.std()

30.229793251029687

In [57]:
# Retorna o desvio padrão para cada coluna (eixo = 0)
d2D.std(axis = 0)

array([27.46197371, 26.61127581, 27.6       , 33.5594994 , 18.31502116,
       24.40163929, 25.3424545 , 38.23820079, 31.42864935, 30.78701025])

In [58]:
# Retorna o desvio padrão para cada linha (eixo = 1)
d2D.std(axis = 1)

array([24.26540748, 26.68632609, 35.66454822, 20.50853481, 26.48471257])

In [59]:
# Retorna a mediana (geral)
np.median(d2D)

47.5

In [60]:
# Retorna a mediana para cada coluna (eixo = 0)
np.median(d2D, axis = 0)

array([42., 43., 53., 84., 32., 27., 61., 57., 78., 29.])

In [61]:
# Retorna a mediana para cada linha (eixo = 1)
np.median(d2D, axis = 1)

array([74.5, 30.5, 40.5, 27.5, 59. ])

### Copiando e concatenando arrays

In [62]:
a2D = np.random.randint(1,50, (4,5))
a2D

array([[31, 41, 32, 22, 30],
       [ 1, 15,  1, 22, 17],
       [26, 34, 39, 37,  7],
       [ 5, 33, 18, 16, 48]])

In [63]:
b2D = np.random.randint(50,100, (4,5))
b2D

array([[50, 99, 71, 80, 60],
       [82, 83, 82, 62, 83],
       [96, 54, 59, 73, 84],
       [63, 88, 59, 98, 53]])

In [64]:
c2D = a2D
c2D

array([[31, 41, 32, 22, 30],
       [ 1, 15,  1, 22, 17],
       [26, 34, 39, 37,  7],
       [ 5, 33, 18, 16, 48]])

In [65]:
# Aparentemente ocorreu uma cópia dos arrays, mas veja o que acontece se alterarmos alguns elementos
c2D[c2D < 20] = -1
c2D

array([[31, 41, 32, 22, 30],
       [-1, -1, -1, 22, -1],
       [26, 34, 39, 37, -1],
       [-1, 33, -1, -1, 48]])

In [66]:
a2D 

array([[31, 41, 32, 22, 30],
       [-1, -1, -1, 22, -1],
       [26, 34, 39, 37, -1],
       [-1, 33, -1, -1, 48]])

Os elementos de a2D também foram alterados. :-(

In [67]:
# Redefinindo os elementos de a2D
a2D = np.random.randint(1,50, (4,5))
a2D

array([[29, 21, 31, 42,  1],
       [20, 46, 23, 43, 10],
       [40, 48, 16, 26, 10],
       [ 2, 35,  1,  5,  8]])

In [68]:
# Forma correta de copiar um array parece que com a forma de copiar uma lista
c2D = a2D.copy()
c2D

array([[29, 21, 31, 42,  1],
       [20, 46, 23, 43, 10],
       [40, 48, 16, 26, 10],
       [ 2, 35,  1,  5,  8]])

In [69]:
c2D[c2D < 20] = -1
c2D

array([[29, 21, 31, 42, -1],
       [20, 46, 23, 43, -1],
       [40, 48, -1, 26, -1],
       [-1, 35, -1, -1, -1]])

In [70]:
a2D

array([[29, 21, 31, 42,  1],
       [20, 46, 23, 43, 10],
       [40, 48, 16, 26, 10],
       [ 2, 35,  1,  5,  8]])

Agora sim!!!

### Ordenando os elementos de um array

In [71]:
a1D = np.random.randint(1,100, 15)
a1D

array([31, 71, 22, 26, 18, 89, 75, 71, 64, 32, 57, 47, 12, 42, 52])

In [72]:
a1D.sort()
a1D

array([12, 18, 22, 26, 31, 32, 42, 47, 52, 57, 64, 71, 71, 75, 89])

In [73]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[90, 22, 88, 35, 22, 56, 13, 95, 28, 72],
       [48, 71, 40,  9, 42, 20, 10, 81, 43, 57],
       [62, 41, 64, 23, 37, 16, 25, 19, 71, 66],
       [ 9, 92, 85, 64, 71, 70, 80, 93, 70, 65],
       [23, 35, 64, 49,  1, 94, 72, 36, 30, 55],
       [14, 31, 58,  1, 26, 64, 58,  4, 18, 50]])

In [74]:
a2D.sort() # Por padrão ordena o maior eixo (nesse caso o eixo 1, linhas)
a2D

array([[13, 22, 22, 28, 35, 56, 72, 88, 90, 95],
       [ 9, 10, 20, 40, 42, 43, 48, 57, 71, 81],
       [16, 19, 23, 25, 37, 41, 62, 64, 66, 71],
       [ 9, 64, 65, 70, 70, 71, 80, 85, 92, 93],
       [ 1, 23, 30, 35, 36, 49, 55, 64, 72, 94],
       [ 1,  4, 14, 18, 26, 31, 50, 58, 58, 64]])

In [75]:
a2D.sort(axis=0) # Ordenando pelo eixo 0 (colunas)
a2D

array([[ 1,  4, 14, 18, 26, 31, 48, 57, 58, 64],
       [ 1, 10, 20, 25, 35, 41, 50, 58, 66, 71],
       [ 9, 19, 22, 28, 36, 43, 55, 64, 71, 81],
       [ 9, 22, 23, 35, 37, 49, 62, 64, 72, 93],
       [13, 23, 30, 40, 42, 56, 72, 85, 90, 94],
       [16, 64, 65, 70, 70, 71, 80, 88, 92, 95]])

In [76]:
a2D = np.random.randint(1,100, (6,10))
a2D

array([[62, 58, 52,  6, 10, 60,  5, 49, 79, 19],
       [93, 42, 40, 44, 24, 96, 34, 24, 81, 84],
       [75, 85, 83, 96, 41,  9, 23, 37,  1, 37],
       [89, 96, 49,  5, 17, 53, 56, 97, 12, 32],
       [94, 87, 28, 64, 86,  1, 71, 95, 39, 43],
       [93, 95, 34, 60, 35, 65, 42, 21,  7, 25]])

In [77]:
a2D.sort(axis=1) # Ordenando pelo eixo 1 (linhas)
a2D

array([[ 5,  6, 10, 19, 49, 52, 58, 60, 62, 79],
       [24, 24, 34, 40, 42, 44, 81, 84, 93, 96],
       [ 1,  9, 23, 37, 37, 41, 75, 83, 85, 96],
       [ 5, 12, 17, 32, 49, 53, 56, 89, 96, 97],
       [ 1, 28, 39, 43, 64, 71, 86, 87, 94, 95],
       [ 7, 21, 25, 34, 35, 42, 60, 65, 93, 95]])

### Transposição de arrays

In [78]:
a2D = np.array([[1,2,3,4],[5,6,7,8]])
a2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
a2DT = a2D.T # Retorna a transposta
a2DT

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [80]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
a2D.transpose() # Retorna a transposta

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [82]:
a2D # a2D original não foi transposto

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### Mudando o formato de um array - reshape()

In [83]:
a1D = np.arange(1,25)
a1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [84]:
print(a1D.shape)
a1D.shape = (2,12)
print(a1D.shape)
print(a1D)

(24,)
(2, 12)
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [85]:
a2D_4x6 = a1D.reshape(4,6)
a2D_4x6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [86]:
a1D

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [87]:
a2D_3x8 = a1D.reshape(3,8)
a2D_3x8

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

### Linearização de um array

In [88]:
x = a2D_3x8.flatten()
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [89]:
y = a2D_3x8.ravel()
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

### Combinando/concatenando arrays

In [91]:
a2D = np.random.randint(1,101,(3,9))
a2D

array([[  9,  76,  71,  42,  27,  95,  23,   7,  37],
       [ 21, 100,  13,  63,  90,  80,   5,  29,  48],
       [ 16,  20,  39,  57,  51,  69,  13,  23,  22]])

In [92]:
b2D = np.random.randint(1,101,(5,9))
b2D

array([[21, 44,  4, 21, 70,  1,  7, 31,  8],
       [21, 98,  2, 74, 59, 43, 48, 80, 39],
       [14, 24,  5, 25, 46, 21, 87, 29, 59],
       [27, 54, 61, 61, 72, 13, 11, 51, 26],
       [ 5, 35, 97, 13, 26, 35, 78, 53, 43]])

In [93]:
c2D = np.random.randint(1,101,(5,4))
c2D

array([[24, 17, 79, 90],
       [25, 91, 31, 17],
       [26, 82, 70, 59],
       [24, 30, 41, 95],
       [69, 10, 54, 32]])

In [94]:
# Concatenação de strings usa o operador "+"
str1 = "Python"
str2 = " & "
str3 = "Numpy"
str4 = str1 + str2 + str3
str4

'Python & Numpy'

In [95]:
# O operador "+" aplicado a ndarrays não faz a concatenação, mas tentar somar elemento a elemento
a2D + b2D

ValueError: operands could not be broadcast together with shapes (3,9) (5,9) 

In [96]:
A = np.concatenate((a2D, b2D), axis = 0) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(A)

a2D
[[  9  76  71  42  27  95  23   7  37]
 [ 21 100  13  63  90  80   5  29  48]
 [ 16  20  39  57  51  69  13  23  22]]

b2D
[[21 44  4 21 70  1  7 31  8]
 [21 98  2 74 59 43 48 80 39]
 [14 24  5 25 46 21 87 29 59]
 [27 54 61 61 72 13 11 51 26]
 [ 5 35 97 13 26 35 78 53 43]]

Concatenação
[[  9  76  71  42  27  95  23   7  37]
 [ 21 100  13  63  90  80   5  29  48]
 [ 16  20  39  57  51  69  13  23  22]
 [ 21  44   4  21  70   1   7  31   8]
 [ 21  98   2  74  59  43  48  80  39]
 [ 14  24   5  25  46  21  87  29  59]
 [ 27  54  61  61  72  13  11  51  26]
 [  5  35  97  13  26  35  78  53  43]]


In [97]:
B = np.vstack((a2D, b2D)) # Concatenando pelo eixo das colunas (eixo 0) (empilhamento vertical) 
print("a2D")
print(a2D)
print("")
print("b2D")
print(b2D)
print("")
print("Concatenação")
print(B)

a2D
[[  9  76  71  42  27  95  23   7  37]
 [ 21 100  13  63  90  80   5  29  48]
 [ 16  20  39  57  51  69  13  23  22]]

b2D
[[21 44  4 21 70  1  7 31  8]
 [21 98  2 74 59 43 48 80 39]
 [14 24  5 25 46 21 87 29 59]
 [27 54 61 61 72 13 11 51 26]
 [ 5 35 97 13 26 35 78 53 43]]

Concatenação
[[  9  76  71  42  27  95  23   7  37]
 [ 21 100  13  63  90  80   5  29  48]
 [ 16  20  39  57  51  69  13  23  22]
 [ 21  44   4  21  70   1   7  31   8]
 [ 21  98   2  74  59  43  48  80  39]
 [ 14  24   5  25  46  21  87  29  59]
 [ 27  54  61  61  72  13  11  51  26]
 [  5  35  97  13  26  35  78  53  43]]


In [98]:
C = np.concatenate((b2D, c2D), axis = 1) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(C)

b2D
[[21 44  4 21 70  1  7 31  8]
 [21 98  2 74 59 43 48 80 39]
 [14 24  5 25 46 21 87 29 59]
 [27 54 61 61 72 13 11 51 26]
 [ 5 35 97 13 26 35 78 53 43]]

c2D
[[24 17 79 90]
 [25 91 31 17]
 [26 82 70 59]
 [24 30 41 95]
 [69 10 54 32]]

Concatenação
[[21 44  4 21 70  1  7 31  8 24 17 79 90]
 [21 98  2 74 59 43 48 80 39 25 91 31 17]
 [14 24  5 25 46 21 87 29 59 26 82 70 59]
 [27 54 61 61 72 13 11 51 26 24 30 41 95]
 [ 5 35 97 13 26 35 78 53 43 69 10 54 32]]


In [99]:
D = np.hstack((b2D, c2D)) # Concatenando pelo eixo das linhas (eixo 1) (empilhamento horizontal) 
print("b2D")
print(b2D)
print("")
print("c2D")
print(c2D)
print("")
print("Concatenação")
print(D)

b2D
[[21 44  4 21 70  1  7 31  8]
 [21 98  2 74 59 43 48 80 39]
 [14 24  5 25 46 21 87 29 59]
 [27 54 61 61 72 13 11 51 26]
 [ 5 35 97 13 26 35 78 53 43]]

c2D
[[24 17 79 90]
 [25 91 31 17]
 [26 82 70 59]
 [24 30 41 95]
 [69 10 54 32]]

Concatenação
[[21 44  4 21 70  1  7 31  8 24 17 79 90]
 [21 98  2 74 59 43 48 80 39 25 91 31 17]
 [14 24  5 25 46 21 87 29 59 26 82 70 59]
 [27 54 61 61 72 13 11 51 26 24 30 41 95]
 [ 5 35 97 13 26 35 78 53 43 69 10 54 32]]


### Dividindo arrays

In [100]:
A_splitted = np.vsplit(A,2) # Divisáo vertical (corta no sentido das colunas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted[0])
print("")
print("2a parte")
print(A_splitted[1])

Array original
[[  9  76  71  42  27  95  23   7  37]
 [ 21 100  13  63  90  80   5  29  48]
 [ 16  20  39  57  51  69  13  23  22]
 [ 21  44   4  21  70   1   7  31   8]
 [ 21  98   2  74  59  43  48  80  39]
 [ 14  24   5  25  46  21  87  29  59]
 [ 27  54  61  61  72  13  11  51  26]
 [  5  35  97  13  26  35  78  53  43]]

1a parte
[[  9  76  71  42  27  95  23   7  37]
 [ 21 100  13  63  90  80   5  29  48]
 [ 16  20  39  57  51  69  13  23  22]
 [ 21  44   4  21  70   1   7  31   8]]

2a parte
[[21 98  2 74 59 43 48 80 39]
 [14 24  5 25 46 21 87 29 59]
 [27 54 61 61 72 13 11 51 26]
 [ 5 35 97 13 26 35 78 53 43]]


In [101]:
A_splitted3 = np.hsplit(A,3) # Divisão horizontal (corta no sentido das linhas)
print("Array original")
print(A)
print("")
print("1a parte")
print(A_splitted3[0])
print("")
print("2a parte")
print(A_splitted3[1])
print("")
print("3a parte")
print(A_splitted3[2])

Array original
[[  9  76  71  42  27  95  23   7  37]
 [ 21 100  13  63  90  80   5  29  48]
 [ 16  20  39  57  51  69  13  23  22]
 [ 21  44   4  21  70   1   7  31   8]
 [ 21  98   2  74  59  43  48  80  39]
 [ 14  24   5  25  46  21  87  29  59]
 [ 27  54  61  61  72  13  11  51  26]
 [  5  35  97  13  26  35  78  53  43]]

1a parte
[[  9  76  71]
 [ 21 100  13]
 [ 16  20  39]
 [ 21  44   4]
 [ 21  98   2]
 [ 14  24   5]
 [ 27  54  61]
 [  5  35  97]]

2a parte
[[42 27 95]
 [63 90 80]
 [57 51 69]
 [21 70  1]
 [74 59 43]
 [25 46 21]
 [61 72 13]
 [13 26 35]]

3a parte
[[23  7 37]
 [ 5 29 48]
 [13 23 22]
 [ 7 31  8]
 [48 80 39]
 [87 29 59]
 [11 51 26]
 [78 53 43]]
