# Verificando propriedades de um ndarray

In [1]:
# Importando o NumPy
import numpy as np

In [2]:
# Cria um ndarray com 10 elementos entre 0 e 9
a1D = np.random.randint(0, 10, 10)
a1D

array([5, 4, 7, 7, 5, 5, 6, 7, 4, 9])

In [3]:
a2D = np.random.randint(1, 101, (4,5)) # Cria um ndarray de 4 linhas x 5 colunas com elementos entre 1 e 100
a2D

array([[94, 67,  7, 58, 78],
       [ 7, 61,  2, 16, 88],
       [28, 45, 71, 90, 49],
       [32, 17, 38, 52, 84]])

In [4]:
a3D = np.random.random((3,4,5)) # Cria um ndarray de 3 páginas x 4 linhas x 5 colunas com elementos entre 0 e 1
a3D

array([[[0.00752146, 0.05571635, 0.63902498, 0.3403771 , 0.89324267],
        [0.4103862 , 0.96671823, 0.81622941, 0.83934375, 0.27809035],
        [0.17292038, 0.61088768, 0.85046756, 0.39880134, 0.41301914],
        [0.44813772, 0.42810634, 0.58109306, 0.78400219, 0.76704646]],

       [[0.34644473, 0.06593871, 0.85429528, 0.25392826, 0.58381686],
        [0.66211332, 0.03151962, 0.39434507, 0.62233627, 0.99350239],
        [0.02384114, 0.48930808, 0.75184894, 0.46070685, 0.85534763],
        [0.46947713, 0.6420428 , 0.36751367, 0.40939066, 0.54528544]],

       [[0.37549071, 0.08519018, 0.20546875, 0.30717119, 0.49878849],
        [0.43650241, 0.46005635, 0.5566211 , 0.45559612, 0.03804674],
        [0.44621001, 0.17817966, 0.55008009, 0.56838822, 0.48454027],
        [0.59685459, 0.99432875, 0.62958658, 0.56943209, 0.23163896]]])

### Verificando o formato e quantidade de dimensões de um array - shape e dim

In [5]:
# A propriedade shape retorna o formato do array
a1D.shape

(10,)

In [8]:
a2D.shape

(4, 5)

In [9]:
a3D.shape

(3, 4, 5)

In [10]:
# A propriedade ndim retorna o números de dimensões do array
a1D.ndim

1

In [11]:
a2D.ndim

2

In [12]:
a3D.ndim

3

### Verificando o tamanho das dimensões de um array - len

In [13]:
len(a1D) # Retorna o tamanho da 1a dimensão (quantidade de colunas)

10

In [14]:
len(a2D) # Retorna o tamanho da 1a dimensão (quantidade de linhas)

4

In [15]:
len(a2D[0]) # Retorna o tamanho da 2a dimensão (quantidade de colunas)

5

In [16]:
len(a3D) # Retorna o tamanho da 1a dimensão (quantidade de páginas)

3

In [17]:
len(a3D[0]) # Retorna o tamanho da 2a dimensão (quantidade de linhas)

4

In [18]:
len(a3D[0][0]) # Retorna o tamanho da 3a dimensão (quantidade de colunas)

5

### Verificando a quantidade de elementos de um array - size

In [19]:
a1D.size

10

In [20]:
a2D.size

20

In [21]:
a3D.size

60

### Verificando o tipo dos elementos um array - dtype

In [28]:
a1D.dtype

dtype('int32')

In [29]:
a1D.dtype.name

'int32'

In [30]:
a2D.dtype

dtype('int32')

In [31]:
a2D.dtype.name

'int32'

In [32]:
a3D.dtype

dtype('float64')

In [33]:
a3D.dtype.name

'float64'