# NumPy - Numerical Python

## Criando arrays NumPy

In [1]:
# Importando o NumPy
import numpy as np

### Criando arrays de 1 dimensão

In [2]:
a1D = np.array([1, 2, 3])
a1D

array([1, 2, 3])

In [3]:
# O objeto criado é um ndarray: n-dimensional array
type(a1D)

numpy.ndarray

In [4]:
# Verificando o tipo dos elementos
a1D.dtype

dtype('int32')

In [5]:
b1D = np.array([1, 2, 3], dtype = float)
b1D

array([1., 2., 3.])

In [6]:
b1D.dtype

dtype('float64')

In [7]:
c1D = np.array([1, 2, 3], dtype = str)
c1D

array(['1', '2', '3'], dtype='<U1')

In [8]:
# str > float > int > bool
d1D = np.array([1, 3.14, "NumPy", True])
d1D

array(['1', '3.14', 'NumPy', 'True'], dtype='<U32')

In [15]:
d1D.dtype

dtype('<U32')

In [16]:
e1D = np.array([1, 3.14, False, True])
e1D

array([1.  , 3.14, 0.  , 1.  ])

In [17]:
e1D.dtype

dtype('float64')

In [18]:
f1D = np.array([1, False, True])
f1D

array([1, 0, 1])

In [19]:
f1D.dtype

dtype('int32')

In [20]:
g1D = np.array([False, True])
g1D

array([False,  True])

In [21]:
g1D.dtype

dtype('bool')

### Criando arrays de 2 dimensões

In [22]:
a2D = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9]])
a2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a2D.dtype

dtype('int32')

### Criando arrays de 3 dimensões

In [25]:
a3D = np.array( [ [ [1,2,3], [4,5,6], [7,8,9] ], [ [11,12,13], [14,15,16], [17,18,19] ], [ [21,22,23], [24,25,26], [27,28,29] ]])
a3D

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]],

       [[21, 22, 23],
        [24, 25, 26],
        [27, 28, 29]]])

## Outras formas de criar arrays

### Arrays preenchidos com zeros - zeros()

In [26]:
# 1 dimensão
azeros = np.zeros(5)
azeros

array([0., 0., 0., 0., 0.])

In [27]:
# 2 dimensões
bzeros = np.zeros((3, 4)) # 3 linhas e 4 colunas
bzeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
# 3 dimensões
czeros = np.zeros((3, 4, 2)) # 3 páginas, 4 linhas e 2 colunas
czeros

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [29]:
# 2 dimensões
dzeros = np.zeros((3, 4), dtype = int) # 3 linhas e 4 colunas
dzeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [61]:
dzerosstr = np.zeros((2,3), dtype = str)
dzerosstr

array([[False, False, False],
       [False, False, False]])

In [64]:
dzerosbool = np.zeros((2,3), dtype = bool)
dzerosbool

array([[False, False, False],
       [False, False, False]])

### Arrays preenchidos com 1's - ones()

In [30]:
# 1 dimensão
a_um_1D = np.ones(5)
a_um_1D

array([1., 1., 1., 1., 1.])

In [31]:
b_um_1D = np.ones(10, dtype = str)
b_um_1D

array(['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [32]:
c_um_1D = np.ones(5, dtype = int)
c_um_1D

array([1, 1, 1, 1, 1])

In [33]:
# 2 dimensões
d_um_2D = np.ones((4, 3)) # 4 linhas e 3 colunas
d_um_2D

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
# 3 dimensões
e_um_3D = np.ones((5, 2, 3)) 
e_um_3D

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [35]:
# 4 dimensões
f_um_4D = np.ones((3, 4, 2, 3)) 
f_um_4D

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

### Arrays preenchidos com faixas de valores - arange()

In [36]:
# Cria um ndarray preenchido com  os elementos de 0 a n-1
# No exemplo abaixo vai criar um ndarray com os elementos 0 a 9
a1D = np.arange(10)
a1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
# Cria um ndarray preenchido com os elementos variando entre o valor inicial e o valor final - 1
# Nesse exemplo vai criar um array com os elementos de 5 a 14
b1D = np.arange(5, 15)
b1D

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
# Cria um ndarray preenchido com os elementos variando entre o valor inicial e o valor final - 1, com um determinado step
# No exemplo vai criar um array com os elementos de 5 a 100, com passo 10. Ou seja: 5, 15, 25...95
c1D = np.arange(5,100, 10)
c1D

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

### Criando arrays preenchidos com valores igualmente espaçados - linspace()

In [39]:
# Cria um array com n elementos entre o valor inicial e valor final, igualmente espaçados
d1D = np.linspace(0,10, 2) # Cria um array com 2 valores entre 0 e 10
d1D

array([ 0., 10.])

In [40]:
e1D = np.linspace(0,10, 4) # Cria um array com 2 valores entre 0 e 10
e1D

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [41]:
f1D = np.linspace(1,1000) # Se não for passada a quantidade de elementos, o padrão é gerar 50 elementos
f1D

array([   1.        ,   21.3877551 ,   41.7755102 ,   62.16326531,
         82.55102041,  102.93877551,  123.32653061,  143.71428571,
        164.10204082,  184.48979592,  204.87755102,  225.26530612,
        245.65306122,  266.04081633,  286.42857143,  306.81632653,
        327.20408163,  347.59183673,  367.97959184,  388.36734694,
        408.75510204,  429.14285714,  449.53061224,  469.91836735,
        490.30612245,  510.69387755,  531.08163265,  551.46938776,
        571.85714286,  592.24489796,  612.63265306,  633.02040816,
        653.40816327,  673.79591837,  694.18367347,  714.57142857,
        734.95918367,  755.34693878,  775.73469388,  796.12244898,
        816.51020408,  836.89795918,  857.28571429,  877.67346939,
        898.06122449,  918.44897959,  938.83673469,  959.2244898 ,
        979.6122449 , 1000.        ])

In [42]:
g1D = np.linspace(1,1000, dtype = int) # gerando int, a função simplesmente corta as casas decimais
g1D

array([   1,   21,   41,   62,   82,  102,  123,  143,  164,  184,  204,
        225,  245,  266,  286,  306,  327,  347,  367,  388,  408,  429,
        449,  469,  490,  510,  531,  551,  571,  592,  612,  633,  653,
        673,  694,  714,  734,  755,  775,  796,  816,  836,  857,  877,
        898,  918,  938,  959,  979, 1000])

In [45]:
h1D = np.linspace(0,50, 10, endpoint = True) # O valor final é incluído
h1D


array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [46]:
i1D = np.linspace(0,50, 10, endpoint = False) # O valor final não é incluído
i1D

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

### Criando arrays preenchidos com um único valor passado por parâmetro - full()

In [47]:
a1D = np.full(10, 5) # ndarray contendo 10 números 5
a1D

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [48]:
a2D = np.full((3, 5), 3)  # ndarray de 3 linhas e 5 colunas contendo o número 3
a2D

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [49]:
a3D = np.full((3, 5, 8), -1)  # ndarray de 3 páginas, 5 linhas e 8 colunas contendo o número -1
a3D

array([[[-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1]],

       [[-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1]],

       [[-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1],
        [-1, -1, -1, -1, -1, -1, -1, -1]]])

### Criando matriz identidade - eye()

In [50]:
ident = np.eye(5) # Cria uma matriz 5x5 preenchida com 1s na diagonal principal e 0 nas posições restantes
ident

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [67]:
ident2 = np.eye(5,4)
ident2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

### Criando matriz com elementos aleatórios

In [51]:
a1D = np.random.randint(0, 100, 10) # Cria um ndarray com 10 elementos entre 0 e 99
a1D

array([44, 17, 64,  1,  6, 37, 53,  7, 14,  4])

In [52]:
a2D = np.random.randint(1, 500, (4,5))
a2D

array([[417, 364, 277, 268, 127],
       [489,  40, 399, 307, 318],
       [125, 191, 364,  31, 208],
       [382, 153, 163, 251, 279]])

In [53]:
# Gerando 10 combinações para a mega-sena
# Valores vão de 1 a 60, 10 páginas, 1 linha, 6 colunas
a3D = np.random.randint(1,61,(10,1,6)) 
a3D

array([[[ 9, 27, 50, 49, 19, 18]],

       [[55,  3, 21, 21, 52, 34]],

       [[32,  7, 12, 27, 32, 26]],

       [[31, 50, 54, 60,  2, 38]],

       [[39, 38, 52, 22, 22, 12]],

       [[34, 24, 36, 42, 52, 18]],

       [[ 2, 51, 35, 18, 42, 28]],

       [[ 8, 30, 29, 45, 48, 59]],

       [[41, 17, 19, 37, 54, 13]],

       [[24, 25, 36, 39, 33, 57]]])

In [54]:
b1D = np.random.random(10) # Cria um ndarray contendo 10 elementos aleatórios entre 0 e 1
b1D

array([0.06298759, 0.58986956, 0.26585057, 0.11519544, 0.95484908,
       0.92579504, 0.50458813, 0.17065539, 0.34130122, 0.90040721])

In [55]:
c2D = np.random.random((4,5)) # Cria um ndarray de 4 linhas e 5 colunas contendo elementos aleatórios entre 0 e 1
c2D

array([[0.73956974, 0.78770534, 0.09637779, 0.99591562, 0.18825907],
       [0.79893103, 0.56913293, 0.64269065, 0.47569808, 0.28499963],
       [0.12976397, 0.69252945, 0.355964  , 0.74926311, 0.88130122],
       [0.68694987, 0.52958416, 0.9627236 , 0.03507293, 0.05586627]])