In [2]:
import numpy as np

In [3]:
series = [[23,45,12,679], [14,48,69,38]]
new_series = np.array(series)
print(new_series.ndim)
print(new_series.shape)

2
(2, 4)


In [5]:
a1 = np.zeros(10)+4
a2 = np.ones(10)*4
a3 = np.full(10,4)
print(a1)
print(a2)
print(a3)

[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
[4 4 4 4 4 4 4 4 4 4]


In [4]:
dataset = np.array(['paul', 'jacob', 'vince', 'paul', 'miky', 'larence', 'warren'])
print(dataset == 'paul')

[ True False False  True False False False]


In [5]:
percentiles = [98, 76.37, 55.55, 69, 88]
first_subject = np.array(percentiles)
print(first_subject.dtype.name)

float64


In [7]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[::2] = -1
print(arr)

[-1  1 -1  3 -1  5 -1  7 -1  9]


In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 0] = -1
print(arr)

[-1  1 -1  3 -1  5 -1  7 -1  9]


In [9]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[-2::-2] = -1
print(arr)

[-1  1 -1  3 -1  5 -1  7 -1  9]


In [10]:
arr = np.eye(5)
arr[arr == 0] = -1
print(arr)

[[ 1. -1. -1. -1. -1.]
 [-1.  1. -1. -1. -1.]
 [-1. -1.  1. -1. -1.]
 [-1. -1. -1.  1. -1.]
 [-1. -1. -1. -1.  1.]]


In [11]:
arr = np.eye(5)
print(arr)
arr[arr != 1] = -1
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 1. -1. -1. -1. -1.]
 [-1.  1. -1. -1. -1.]
 [-1. -1.  1. -1. -1.]
 [-1. -1. -1.  1. -1.]
 [-1. -1. -1. -1.  1.]]


In [12]:
arr = np.eye(5)
print(arr)
arr = arr - (np.eye(5) + 1)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.]]


In [14]:
testearr = np.eye(5) + 1
print(testearr)

[[2. 1. 1. 1. 1.]
 [1. 2. 1. 1. 1.]
 [1. 1. 2. 1. 1.]
 [1. 1. 1. 2. 1.]
 [1. 1. 1. 1. 2.]]


In [16]:
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
